server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;
    absolute_redirect off;
    port_in_redirect off;

    location = /install {
        return 301 /install/;
    }

    location /install/ {
        try_files $uri $uri/ /install/index.php?$query_string;
    }

    location ~ ^/install/.*\.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_PORT 8080;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param REMOTE_ADDR 127.0.0.1;
        fastcgi_param HTTP_X_FORWARDED_FOR 127.0.0.1;
    }

    location = /setup {
        return 302 /install/index.php;
    }

    location = /setup/ {
        return 302 /install/index.php;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_PORT 8080;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param REMOTE_ADDR 127.0.0.1;
        fastcgi_param HTTP_X_FORWARDED_FOR 127.0.0.1;
    }

    location ~ /\.ht {
        deny all;
    }
}
